# Build and publish kosu-monorepo CI and development images to GCR

steps:

# Pull images to build from cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/go-kosu-ci:latest || exit 0;
      docker pull gcr.io/$PROJECT_ID/node-ci:latest || exit 0;

# build and tag go-kosu ci image 
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "--cache-from", "gcr.io/kosu-io/go-kosu-ci:latest",
    "-t", "gcr.io/kosu-io/go-kosu-ci:$SHORT_SHA",
    "-t", "gcr.io/kosu-io/go-kosu-ci:latest",
    "-f", "./packages/dev-images/ci/go-kosu.Dockerfile",
    "./packages/dev-images"
  ]

# build and tag nodejs ci image 
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "--cache-from", "gcr.io/kosu-io/node-ci:latest",
    "-t", "gcr.io/kosu-io/node-ci:$SHORT_SHA",
    "-t", "gcr.io/kosu-io/node-ci:latest",
    "-f", "./packages/dev-images/ci/node.Dockerfile",
    "."
  ]

images: [
  # go-kosu ci image
  "gcr.io/kosu-io/go-kosu-ci:$SHORT_SHA", "gcr.io/kosu-io/go-kosu-ci:latest",

  # general nodejs ci image
  "gcr.io/kosu-io/node-ci:$SHORT_SHA", "gcr.io/kosu-io/node-ci:latest",
]

options: 
 machineType: "N1_HIGHCPU_8"