# Main CD config (build and publish documentation and binaries)

steps:

# =================
# INSTALL AND BUILD
# =================

- name: gcr.io/kosu-io/node-ci:latest
  entrypoint: yarn
  args: ["install"]

- name: gcr.io/kosu-io/node-ci:latest
  entrypoint: yarn
  args: ["build"]

# ==========
# BUILD DOCS
# ==========

- name: gcr.io/kosu-io/node-ci:latest
  entrypoint: yarn
  args: ["docs"]

# ============
# PUBLISH DOCS
# ============

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m", 
    "rsync", 
    "-r", "-c", "-d", 
    "./packages/kosu.js/docs",
    "gs://kosu-docs/kosu.js"
  ]

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m", 
    "rsync", 
    "-r", "-c", "-d", 
    "./packages/kosu-system-contracts/docs",
    "gs://kosu-docs/kosu-system-contracts"
  ]

# ================
# PUBLISH BINARIES
# ================

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m",
    "cp", 
    "./packages/go-kosu/kosud",
    "gs://kosu-binaries/go-kosu/",
  ]

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m",
    "cp", 
    "./packages/go-kosu/kosu-cli",
    "gs://kosu-binaries/go-kosu/",
  ]

# ================
# DEPLOY DOCS SITE
# ================

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m", 
    "rsync", 
    "-r", "-c", "-d", 
    "./packages/kosu.js/docs",
    "./packages/kosu-docs/docs/kosu.js"
  ]

- name: "gcr.io/cloud-builders/gsutil"
  args: [
    "-m", 
    "rsync", 
    "-r", "-c", "-d", 
    "./packages/kosu-system-contracts/docs",
    "./packages/kosu-docs/docs/kosu-system-contracts"
  ]

- name: "gcr.io/kosu-io/node-ci:latest"
  entrypoint: "yarn"
  args: [
    "lerna", 
    "run", 
    "--scope",
    "@kosu/documentation", 
    "compile",
  ]

- name: gcr.io/cloud-builders/gsutil
  args: [
    "-m", "rsync", "-r", "-c", "-d",
    "./packages/kosu-docs/docs/.vuepress/dist",
    "gs://docs.kosu.io",
  ]

options: 
 machineType: "N1_HIGHCPU_8"