/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { CompilerOpts, ContractAbi, ContractNetworks, EvmOutput } from "ethereum-types";

import * as AuthorizedAddresses from "../generated-artifacts/AuthorizedAddresses.json";
import * as BasicTradeSubContract from "../generated-artifacts/BasicTradeSubContract.json";
import * as SignatureValidatorSubContract from "../generated-artifacts/SignatureValidatorSubContract.json";
import * as EventEmitter from "../generated-artifacts/EventEmitter.json";
import * as KosuToken from "../generated-artifacts/KosuToken.json";
import * as OrderGateway from "../generated-artifacts/OrderGateway.json";
import * as PosterRegistry from "../generated-artifacts/PosterRegistry.json";
import * as TestToken from "../generated-artifacts/TestToken.json";
import * as Treasury from "../generated-artifacts/Treasury.json";
import * as ValidatorRegistry from "../generated-artifacts/ValidatorRegistry.json";
import * as Voting from "../generated-artifacts/Voting.json";
import * as ZeroExV2SubContract from "../generated-artifacts/ZeroExV2SubContract.json";

export const artifacts = {
    AuthorizedAddresses: AuthorizedAddresses as KosuContractArtifact,
    EventEmitter: EventEmitter as KosuContractArtifact,
    OrderGateway: OrderGateway as KosuContractArtifact,
    KosuToken: KosuToken as KosuContractArtifact,
    PosterRegistry: PosterRegistry as KosuContractArtifact,
    Treasury: Treasury as KosuContractArtifact,
    ValidatorRegistry: ValidatorRegistry as KosuContractArtifact,
    Voting: Voting as KosuContractArtifact,
    ZeroExV2SubContract: ZeroExV2SubContract as KosuContractArtifact,
    BasicTradeSubContract: BasicTradeSubContract as KosuContractArtifact,
    SignatureValidatorSubContract: SignatureValidatorSubContract as KosuContractArtifact,
    TestToken: TestToken as KosuContractArtifact,
};

// The below avoids compiler errors due to mis-matched types from devDoc output.

export interface KosuContractArtifact extends KosuContractVersionData {
    schemaVersion: string;
    contractName: string;
    networks: ContractNetworks;
}

interface KosuContractVersionData {
    compiler: CompilerOpts;
    sources: {
        [sourceName: string]: {
            id: number;
        };
    };
    sourceCodes: {
        [sourceName: string]: string;
    };
    sourceTreeHashHex: string;
    compilerOutput: KosuStandardContractOutput;
}

interface KosuStandardContractOutput {
    abi: ContractAbi;
    evm: EvmOutput;
    devdoc?: KosuDevDocOutput;
}

interface KosuDevDocOutput {
    title?: string;
    author?: string;
    methods?: {
        [signature: string]: {
            details?: string;
            params?: {
                [name: string]: string;
            };
            return?: string;
        };
    };
}
