/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from "ethereum-types";

import * as AuthorizedAddresses from "../generated-artifacts/AuthorizedAddresses.json";
import * as EventEmitter from "../generated-artifacts/EventEmitter.json";
import * as KosuToken from "../generated-artifacts/KosuToken.json";
import * as OrderGateway from "../generated-artifacts/OrderGateway.json";
import * as PosterRegistry from "../generated-artifacts/PosterRegistry.json";
import * as PosterRegistryProxy from "../generated-artifacts/PosterRegistryProxy.json";
import * as Treasury from "../generated-artifacts/Treasury.json";
import * as ValidatorRegistry from "../generated-artifacts/ValidatorRegistry.json";
import * as Voting from "../generated-artifacts/Voting.json";
import * as BasicTradeSubContract from "../generated-artifacts/BasicTradeSubContract.json";
export const artifacts = {
    AuthorizedAddresses: AuthorizedAddresses as ContractArtifact,
    EventEmitter: EventEmitter as ContractArtifact,
    OrderGateway: OrderGateway as ContractArtifact,
    PosterRegistryProxy: PosterRegistryProxy as ContractArtifact,
    KosuToken: KosuToken as ContractArtifact,
    PosterRegistry: PosterRegistry as ContractArtifact,
    Treasury: Treasury as ContractArtifact,
    ValidatorRegistry: ValidatorRegistry as ContractArtifact,
    Voting: Voting as ContractArtifact,
    BasicTradeSubContract: BasicTradeSubContract as ContractArtifact,
};
