# Kosu monorepo CI config file (last updated: 24 June 2019)

kind: pipeline
name: tests

steps:
  - name: prettier-project
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn prettier:ci
    depends_on:
      - clone

  - name: build-project
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn
      - yarn setup:ci
      - cd packages/kosu-system-contracts
      - yarn migrate:ci
    depends_on:
      - clone
    when:
      changeset:
        includes:
          [
            .drone.yml,
            package.json,
            tsconfig.json,
            packages/go-kosu/**/*.*,
            packages/kosu-sdk-contracts/**/*.*,
            packages/kosu-system-contracts/**/*.*,
            packages/kosu.js/**/*.*,
            packages/tslint-config/**/*.*,
            packages/tsc-config/**/*.*,
          ]

  - name: npm-tests
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn test:ci
    depends_on:
      - build-project
    when:
      changeset:
        includes:
          [
            .drone.yml,
            packages/kosu-sdk-contracts/**/*.*,
            packages/kosu-system-contracts/**/*.*,
            packages/kosu.js/**/*.*,
            packages/tslint-config/**/*.*,
            packages/tsc-config/**/*.*,
          ]

  - name: solidity-tests
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn contracts:test:ci
    depends_on:
      - build-project
    when:
      changeset:
        includes:
          [
            .drone.yml,
            packages/kosu-sdk-contracts/**/*.*,
            packages/kosu-system-contracts/**/*.*,
            packages/tslint-config/**/*.*,
            packages/tsc-config/**/*.*,
            tsconfig.json,
          ]

  - name: go-kosu
    image: gcr.io/kosu-io/go-kosu-ci:latest
    pull: always
    environment:
      WEB3_TEST_URI: ws://kosu-geth:8546
    commands:
      - cd packages/go-kosu
      - make ci
    depends_on:
      - build-project
    when:
      changeset:
        includes:
          [
            .drone.yml,
            packages/go-kosu/**/*.*,
            packages/kosu-sdk-contracts/**/*.*,
            packages/kosu-system-contracts/**/*.*,
          ]

services:
    - name: kosu-geth
      image: gcr.io/kosu-io/kosu-geth:latest
      pull: always
      ports:
          - 8545
          - 8546

trigger:
    event:
        - pull_request

# UNTESTED
# ---
# kind: pipeline
# name: go-kosu-release
#
# release:
#     image: golang:1.12
#     secrets: [github_token]
#     commands:
#      curl -sL https://git.io/goreleaser | bash
#     when:
#       event: tag
