kind: pipeline
name: default

steps:
  - name: node-tests
    image: node:lts
    commands:
    - apk add --update --no-cache netcat-openbsd
    - yarn global add typescript
    - yarn
    - yarn build
    - yarn test