# Kosu-monorepo CI configuration file (last updated 4 June 2019)

kind: pipeline
name: node-tests

steps:
  - name: restore-project
    image: drillster/drone-volume-cache
    volumes:
      - name: project
    settings:
      rebuild: true
      mount:
        - .

  - name: node-projects
    image: gcr.io/kosu-io/node-ci:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn
      - yarn prettier:ci
      - yarn lint
      - yarn build
      - yarn test:ci

  - name: rebuild-node-modules
    image: drillster/drone-volume-cache
    volumes:
      - name: proejct
    settings:
      rebuild: true
      mount:
        - .

volumes:
  - name: project
    host:
      path: /var/lib/project

services:
  - name: kosu-geth
    image: gcr.io/kosu-io/kosu-geth:latest
    pull: always
    ports:
      - 8545

# Pull request trigger is not correctly causing build to start on fresh pull request.
trigger:
  event:
    include:
    - pull_request
  changeset:
    includes: [
      .drone.yml,
      packages/kosu.js/**/*.*,
      packages/dev-images/**/*.*,
      packages/kosu-sdk-contracts/**/*.*,
      packages/kosu-system-contracts/**/*.*,
      packages/web-helpers/**/*.*,
      packages/kosu-geth/**/*.*,
      packages/tslint-config/**/*.*,
      packages/tsc-config/**/*.*
    ]

---
kind: pipeline
name: golang-tests

steps:
  - name: go-kosu
    image: gcr.io/kosu-io/go-kosu-ci:latest
    pull: always
    environment:
      ETHEREUM_TEST_ADDRESS: wss://ethnet.zaidan.io/ws/ropsten
    commands:
    - cd packages/go-kosu
    - make ci

trigger:
  event:
    - pull_request
  changeset:
    includes: [
      .drone.yml,
      packages/go-kosu/**/*.*,
      packages/kosu-system-contracts/**/*.*
    ]

# UNTESTED
# ---
# kind: pipeline
# name: go-kosu-release
#  
# release:
#     image: golang:1.12
#     secrets: [github_token]
#     commands:
#      curl -sL https://git.io/goreleaser | bash
#     when:
#       event: tag
