kind: pipeline
name: default

steps:
  - name: node-tests
    image: node:lts
    commands:
    - apt-get update
    - apt-get install -y netcat
    - yarn global add typescript
    - yarn
    - yarn build
    - yarn test