---
kind: pipeline
name: tests

platform:
  os: linux
  arch: amd64

steps:
- name: prettier_project
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn prettier:ci

- name: build-project
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn
  - yarn setup:ci
  - yarn migrate:ci
  - WEB3_URI=http://go-kosu-ci-geth:8545 yarn migrate:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546

- name: npm-tests
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn test:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546
  depends_on:
  - build-project

- name: solidity
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn contracts:test:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546
  depends_on:
  - build-project
  - npm-tests

- name: kosu-node-0
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud start -H ./testnet/node0 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project

- name: kosu-node-1
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud start -H ./testnet/node1 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project

- name: kosu-node-2
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud start -H ./testnet/node2 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project

- name: kosu-node-3
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud start -H ./testnet/node3 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project

- name: go-kosu
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  commands:
  - cd packages/go-kosu
  - export KOSU_TEST_NODES=$(pwd)/testnet/node0@kosu-node-1:26657,$(pwd)/testnet/node1@kosu-node-1:26657,$(pwd)/testnet/node2@kosu-node-1:26657,$(pwd)/testnet/node3@kosu-node-1:26657
  - make ci
  depends_on:
  - build-project
  - kosu-node-0
  - kosu-node-1
  - kosu-node-2
  - kosu-node-3

services:
- name: kosu-geth
  pull: always
  image: gcr.io/kosu-io/kosu-test-geth:latest
  ports:
  - 8545
  - 8546

- name: go-kosu-ci-geth
  pull: always
  image: gcr.io/kosu-io/kosu-test-geth:latest
  ports:
  - 8545
  - 8546

trigger:
  event:
  - pull_request
  - tag

---
kind: pipeline
name: release

platform:
  os: linux
  arch: amd64

steps:
- name: yarn
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn
  - yarn build
  - yarn prettier
  - npm-cli-login
  - git checkout .
  - yarn lerna publish from-package --yes
  environment:
    NPM_EMAIL:
      from_secret: npm_email
    NPM_PASS:
      from_secret: npm_password
    NPM_USER:
      from_secret: npm_user

- name: gorelease
  pull: always
  image: gcr.io/kosu-io/go-kosu
  commands:
  - git fetch --tags
  - cd ./packages/go-kosu
  - curl -sL https://git.io/goreleaser | bash -s -- --skip-validate
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    ref:
    - refs/tags/@kosu/go-kosu*
  depends_on:
  - yarn

- name: docker
  image: plugins/gcr
  settings:
    context: ./packages/go-kosu
    dockerfile: ./packages/go-kosu/Dockerfile.binaries
    json_key:
      from_secret: google_credentials
    registry: gcr.io
    repo: kosu-test-network/go-kosu
    tags:
    - latest
  when:
    ref:
    - refs/tags/@kosu/go-kosu*
  depends_on:
  - gorelease

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 34.68.74.152
    key:
      from_secret: ssh_ci_key
    script:
    - docker run --rm -d gcr.io/kosu-test-network/go-kosu kosud start
    username: ci
  when:
    ref:
    - refs/tags/@kosu/go-kosu*
  depends_on:
  - docker

trigger:
  event:
  - tag

depends_on:
- tests

...
