# Kosu monorepo CI config file (last updated: 24 June 2019)

kind: pipeline
name: tests

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: prettier-project
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    volumes:
      - name: deps
        path: /go
    commands:
      - yarn prettier:ci
    depends_on:
      - clone

  - name: build-project
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn
      - yarn setup:ci
      - cd packages/kosu-system-contracts
      - yarn migrate:ci
    volumes:
      - name: deps
        path: /go
    depends_on:
      - clone

  - name: npm-tests
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn test:ci
    volumes:
      - name: deps
        path: /go
    depends_on:
      - build-project

  - name: solidity-tests
    image: gcr.io/kosu-io/node-lts:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - yarn contracts:test:ci
    volumes:
      - name: deps
        path: /go
    depends_on:
      - build-project

  - name: go-kosu
    image: gcr.io/kosu-io/go-kosu-ci:latest
    pull: always
    environment:
      WEB3_TEST_URI: ws://kosu-geth:8546
    volumes:
      - name: deps
        path: /go
    commands:
      - cd packages/go-kosu
      - make ci
    depends_on:
      - build-project
  
  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: deps
        path: /go
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event: tag
    depends_on:
      - build-project

volumes:
  - name: deps
    temp: {}

services:
  - name: kosu-geth
    image: gcr.io/kosu-io/kosu-geth:0.1.1
    pull: always
    ports:
      - 8545
      - 8546
