kind: pipeline
name: node-tests

steps:
  - name: npm-projects
    image: gcr.io/kosu-io/node-ci:latest
    pull: always
    environment:
      WEB3_URI: http://kosu-ganache:8545
    commands:
      - yarn
      - yarn prettier:ci
      - yarn lint
      - yarn build
      - yarn test:ci

services:
  - name: kosu-ganache
    image: gcr.io/kosu-io/kosu-geth:latest
    pull: always
    ports:
      - 8545

trigger:
  event:
   - pull_request
  changeset:
    includes: [
      .drone.yml,
      packages/kosu.js/**/*.*,
      packages/dev-images/**/*.*,
      packages/kosu-sdk-contracts/**/*.*,
      packages/kosu-system-contracts/**/*.*
    ]

---
kind: pipeline
name: golang-tests

steps:
  - name: go-kosu
    image: gcr.io/kosu-io/go-kosu-ci:latest
    pull: always
    environment:
      ETHEREUM_TEST_ADDRESS: wss://ropsten.infura.io/ws
    commands:
    - cd packages/go-kosu
    - make ci

trigger:
  event:
    - pull_request
  changeset:
    includes: [
      .drone.yml,
      packages/go-kosu/**/*.*,
      packages/kosu-system-contracts/**/*.*
    ]

# UNTESTED
# ---
# kind: pipeline
# name: go-kosu-release
#  
# release:
#     image: golang:1.12
#     secrets: [github_token]
#     commands:
#      curl -sL https://git.io/goreleaser | bash
#     when:
#       event: tag
