kind: pipeline
name: default

steps:
  - name: node-tests
    image: gcr.io/kosu-io/node
    commands:
    - yarn
    - yarn build
    - yarn test

  - name: go-kosu-tests
    image: gcr.io/kosu-io/go-kosu-ci
    commands:
    - make ci
    
#  release:
#    image: golang:1.12
#    secrets: [github_token]
#    commands:
#      curl -sL https://git.io/goreleaser | bash
#    when:
#      event: tag