# Kosu-monorepo CI configuration file (last updated 4 June 2019)

kind: pipeline
name: node-tests

steps:
  - name: node-projects
    image: gcr.io/kosu-io/node-ci:latest
    volumes:
      - name: node_modules
        path: /drone/src/node_modules
    pull: always
    environment:
      WEB3_URI: http://kosu-geth:8545
    commands:
      - pwd
      - ls
      - touch /node_modules/file
      - yarn
      - yarn prettier:ci
      - yarn lint
      - yarn build
      - yarn test:ci

volumes:
  - name: node_modules
    host:
      path: /var/lib/node_modules

services:
  - name: kosu-geth
    image: gcr.io/kosu-io/kosu-geth:latest
    pull: always
    ports:
      - 8545

# Pull request trigger is not correctly causing build to start on fresh pull request.
trigger:
  event:
    include:
    - pull_request
  changeset:
    includes: [
      .drone.yml,
      packages/kosu.js/**/*.*,
      packages/dev-images/**/*.*,
      packages/kosu-sdk-contracts/**/*.*,
      packages/kosu-system-contracts/**/*.*,
      packages/web-helpers/**/*.*,
      packages/kosu-geth/**/*.*,
      packages/tslint-config/**/*.*,
      packages/tsc-config/**/*.*
    ]

# UNTESTED
# ---
# kind: pipeline
# name: go-kosu-release
#  
# release:
#     image: golang:1.12
#     secrets: [github_token]
#     commands:
#      curl -sL https://git.io/goreleaser | bash
#     when:
#       event: tag
