---
kind: pipeline
name: tests

platform:
  os: linux
  arch: amd64

steps:
- name: prettier_project
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn prettier:ci
  volumes:
  - name: cache
    path: /

- name: build-project
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn
  - yarn setup:ci
  - cd packages/kosu-system-contracts
  - yarn migrate:ci
  - WEB3_URI=http://go-kosu-ci-geth:8545 yarn migrate:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546
  volumes:
  - name: cache
    path: /

- name: npm-tests
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn test:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546
  depends_on:
  - build-project
  volumes:
  - name: cache
    path: /

- name: solidity
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - yarn contracts:test:ci
  environment:
    WEB3_URI: http://kosu-geth:8545
    WEB3_URI_WS: ws://kosu-geth:8546
  depends_on:
  - build-project
  volumes:
  - name: cache
    path: /

- name: kosu-node-0
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud -H ./testnet/node0 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project

- name: kosu-node-1
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud -H ./testnet/node1 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project
  volumes:
  - name: cache
    path: /

- name: kosu-node-2
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud -H ./testnet/node2 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project
  volumes:
  - name: cache
    path: /

- name: kosu-node-3
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  detach: true
  commands:
  - cd packages/go-kosu
  - ./kosud -H ./testnet/node3 -E ws://go-kosu-ci-geth:8546
  depends_on:
  - build-project
  volumes:
  - name: cache
    path: /

- name: go-kosu
  pull: always
  image: gcr.io/kosu-io/go-kosu-ci:latest
  commands:
  - cd packages/go-kosu
  - "export KOSU_TEST_NODES=$(pwd)/testnet/node0@kosu-node-1:26657,$(pwd)/testnet/node1@kosu-node-1:26657,$(pwd)/testnet/node2@kosu-node-1:26657,$(pwd)/testnet/node3@kosu-node-1:26657"
  - make ci
  depends_on:
  - build-project
  - kosu-node-0
  - kosu-node-1
  - kosu-node-2
  - kosu-node-3
  volumes:
  - name: cache
    path: /

- name: release
  pull: always
  image: gcr.io/kosu-io/node-ci:latest
  commands:
  - npm-cli-login
  - git checkout .
  - git clean -fd
  - git reset --hard
  - yarn lerna publish from-package --yes
  environment:
    NPM_EMAIL:
      from_secret: npm_email
    NPM_PASS:
      from_secret: npm_password
    NPM_USER:
      from_secret: npm_user
  when:
    event:
    - tag
    status:
    - success
  depends_on:
  - go-kosu
  - solidity
  - npm-tests
  volumes:
  - name: cache
    path: /

services:
- name: kosu-geth
  pull: always
  image: gcr.io/kosu-io/kosu-test-geth:latest
  ports:
  - 8545
  - 8546

- name: go-kosu-ci-geth
  pull: always
  image: gcr.io/kosu-io/kosu-test-geth:latest
  ports:
  - 8545
  - 8546

trigger:
  event:
  - pull_request
  - tag

volumes:
- name: cache
  temp: {}
...
