language: generic

jobs:
  include:
    - stage: build_and_test
      language: node_js
      name: NodeJS
      node_js:
        - "8"
        - "10"
        - "11"
      before_script:
        - yarn global add typescript
      script:
        - yarn build
        - yarn test

    - stage: build_and_test
      language: go
      name: Go
      go: 1.12
      env:
        global:
          GO111MODULE=on
      cache:
        directories:
          - $GOCACHE

      before_script:
        - cd packages/go/go-test
      script:
        - go version
        - go env
        - go mod download
        - go mod verify
        - go test -v ./...

stages:
  - build_and_test
  - name: release
    if: tag IS present
