language: generic

jobs:
  include:
    - stage: build_and_test
      name: NodeJS
      node_js:
        - "8"
        - "10"
        - "11"
      before_script:
        - yarn global add typescript
      script:
        - yarn build
        - yarn test

    - stage: build_and_test
      name: Go
      go:
        - "1.11"
        - "1.12"
      before_script:
        - cd packages/go/go-test
      script:
        - go test -v ./...

stages:
  - build_and_test
  - name: release
    if: tag IS present
