matrix:
  include:
    - stage: install
      script:
        - yarn --production=false
        - yarn build

    - stage: node tests
      language: node_js
      node_js:
        - "8"
        - "10"
        - "11"
      before_script:
        - yarn global add typescript
      script:
        - yarn test

    - stage: go tests
      language: go
      go:
        - "1.11"
        - "1.12"
      before_script:
        - cd packages/go/go-test
      script:
        - go test -v ./...
