# Kosu monorepo CD config for GCP cloud-build (last updated 18 June 19)

steps:

 # ===============
 # BUILD CI IMAGES
 # ===============

# Pull images to build from cache
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker pull gcr.io/$PROJECT_ID/go-kosu-ci:latest || exit 0; docker pull gcr.io/$PROJECT_ID/node-ci:latest || exit 0; docker pull gcr.io/$PROJECT_ID/kosu-geth:latest || exit 0;

# build and tag go-kosu ci image 
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "--cache-from", "gcr.io/kosu-io/go-kosu-ci:latest",
    "-t", "gcr.io/kosu-io/go-kosu-ci:$SHORT_SHA",
    "-t", "gcr.io/kosu-io/go-kosu-ci:latest",
    "-f", "./packages/dev-images/ci/go-kosu.Dockerfile",
    "./packages/dev-images"
  ]

# build and tag nodejs ci image 
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "--cache-from", "gcr.io/kosu-io/node-ci:latest",
    "-t", "gcr.io/kosu-io/node-ci:$SHORT_SHA",
    "-t", "gcr.io/kosu-io/node-ci:latest",
    "-f", "./packages/dev-images/ci/node.Dockerfile",
    "./packages/dev-images"
  ]

# build and tag kosu-geth
- name: "gcr.io/cloud-builders/docker"
  args: [
    "build",
    "--cache-from", "gcr.io/kosu-io/kosu-geth:latest",
    "-t", "gcr.io/kosu-io/kosu-geth:$SHORT_SHA",
    "-t", "gcr.io/kosu-io/kosu-geth:latest",
    "-f", "./packages/kosu-geth/Dockerfile",
    "./packages/kosu-geth"
  ]

 # =============
 # GENERATE DOCS
 # =============

- name: "gcr.io/cloud-builders/yarn"
  args: ["install"]
- name: "gcr.io/cloud-builders/yarn"
  args: ["docs"]

# =============
# DOCKER IMAGES
# =============

images: [
  # go-kosu ci image
  "gcr.io/kosu-io/go-kosu-ci:$SHORT_SHA", "gcr.io/kosu-io/go-kosu-ci:latest",

  # general nodejs ci image
  "gcr.io/kosu-io/node-ci:$SHORT_SHA", "gcr.io/kosu-io/node-ci:latest",

  # kosu-geth poa test image
  "gcr.io/kosu-io/kosu-geth:$SHORT_SHA", "gcr.io/kosu-io/kosu-geth:latest",
]

# =========
# SAVE DOCS
# =========

artifacts: 
  objects:
    location: "gs://kosu-docs/kosu.js"
    paths: ["packages/kosu.js/docs/*"]
  objects:
    location: "gs://kosu-docs/kosu-system-contracts"
    paths: ["packages/kosu-system-contracts/docs/*"]

# ======
# CONFIG
# ======

options: 
 machineType: "N1_HIGHCPU_8"