steps:
  - name: gcr.io/cloud-builders/gsutil
    args: [
      "-m", "rsync", "-r", "-c", "-d",
      "gs://kosu-docs/kosu.js", "./docs/kosu.js"
    ]
  
  - name: gcr.io/cloud-builders/gsutil
    args: [
      "-m", "rsync", "-r", "-c", "-d",
      "gs://kosu-docs/kosu-system-contracts", "./docs/kosu-system-contracts"
    ]
  
  - name: node:lts
    entrypoint: yarn
    args: [
      "install",
    ]

  - name: node:lts
    entrypoint: yarn
    args: [
      "build",
    ]

  - name: gcr.io/cloud-builders/gsutil
    args: [
      "-m", "rsync", "-r", "-c", "-d",
      "./docs/.vuepress/dist", "gs://docs.kosu.io"
    ]

options: 
 machineType: "N1_HIGHCPU_8"
