// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionWitness_Subject int32

const (
	TransactionWitness_POSTER    TransactionWitness_Subject = 0
	TransactionWitness_VALIDATOR TransactionWitness_Subject = 1
)

var TransactionWitness_Subject_name = map[int32]string{
	0: "POSTER",
	1: "VALIDATOR",
}

var TransactionWitness_Subject_value = map[string]int32{
	"POSTER":    0,
	"VALIDATOR": 1,
}

func (x TransactionWitness_Subject) String() string {
	return proto.EnumName(TransactionWitness_Subject_name, int32(x))
}

func (TransactionWitness_Subject) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9, 0}
}

//*
// BigInt
type BigInt struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigInt) Reset()         { *m = BigInt{} }
func (m *BigInt) String() string { return proto.CompactTextString(m) }
func (*BigInt) ProtoMessage()    {}
func (*BigInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *BigInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigInt.Unmarshal(m, b)
}
func (m *BigInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigInt.Marshal(b, m, deterministic)
}
func (m *BigInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigInt.Merge(m, src)
}
func (m *BigInt) XXX_Size() int {
	return xxx_messageInfo_BigInt.Size(m)
}
func (m *BigInt) XXX_DiscardUnknown() {
	xxx_messageInfo_BigInt.DiscardUnknown(m)
}

var xxx_messageInfo_BigInt proto.InternalMessageInfo

func (m *BigInt) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

//*
// RoundInfo
type RoundInfo struct {
	Number               uint64   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	StartsAt             uint64   `protobuf:"varint,2,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt               uint64   `protobuf:"varint,3,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Limit                uint64   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoundInfo) Reset()         { *m = RoundInfo{} }
func (m *RoundInfo) String() string { return proto.CompactTextString(m) }
func (*RoundInfo) ProtoMessage()    {}
func (*RoundInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *RoundInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoundInfo.Unmarshal(m, b)
}
func (m *RoundInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoundInfo.Marshal(b, m, deterministic)
}
func (m *RoundInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoundInfo.Merge(m, src)
}
func (m *RoundInfo) XXX_Size() int {
	return xxx_messageInfo_RoundInfo.Size(m)
}
func (m *RoundInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoundInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoundInfo proto.InternalMessageInfo

func (m *RoundInfo) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RoundInfo) GetStartsAt() uint64 {
	if m != nil {
		return m.StartsAt
	}
	return 0
}

func (m *RoundInfo) GetEndsAt() uint64 {
	if m != nil {
		return m.EndsAt
	}
	return 0
}

func (m *RoundInfo) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

//*
// ConsensusParams
type ConsensusParams struct {
	FinalityThreshold     uint32   `protobuf:"varint,1,opt,name=FinalityThreshold,proto3" json:"FinalityThreshold,omitempty"`
	PeriodLimit           uint32   `protobuf:"varint,2,opt,name=PeriodLimit,proto3" json:"PeriodLimit,omitempty"`
	PeriodLength          uint32   `protobuf:"varint,3,opt,name=PeriodLength,proto3" json:"PeriodLength,omitempty"`
	MaxOrderBytes         uint32   `protobuf:"varint,4,opt,name=MaxOrderBytes,proto3" json:"MaxOrderBytes,omitempty"`
	ConfirmationThreshold uint32   `protobuf:"varint,5,opt,name=ConfirmationThreshold,proto3" json:"ConfirmationThreshold,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ConsensusParams) Reset()         { *m = ConsensusParams{} }
func (m *ConsensusParams) String() string { return proto.CompactTextString(m) }
func (*ConsensusParams) ProtoMessage()    {}
func (*ConsensusParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *ConsensusParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusParams.Unmarshal(m, b)
}
func (m *ConsensusParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusParams.Marshal(b, m, deterministic)
}
func (m *ConsensusParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusParams.Merge(m, src)
}
func (m *ConsensusParams) XXX_Size() int {
	return xxx_messageInfo_ConsensusParams.Size(m)
}
func (m *ConsensusParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusParams proto.InternalMessageInfo

func (m *ConsensusParams) GetFinalityThreshold() uint32 {
	if m != nil {
		return m.FinalityThreshold
	}
	return 0
}

func (m *ConsensusParams) GetPeriodLimit() uint32 {
	if m != nil {
		return m.PeriodLimit
	}
	return 0
}

func (m *ConsensusParams) GetPeriodLength() uint32 {
	if m != nil {
		return m.PeriodLength
	}
	return 0
}

func (m *ConsensusParams) GetMaxOrderBytes() uint32 {
	if m != nil {
		return m.MaxOrderBytes
	}
	return 0
}

func (m *ConsensusParams) GetConfirmationThreshold() uint32 {
	if m != nil {
		return m.ConfirmationThreshold
	}
	return 0
}

type Poster struct {
	Balance              *BigInt  `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	OrderLimit           uint64   `protobuf:"varint,2,opt,name=orderLimit,proto3" json:"orderLimit,omitempty"`
	StreamLimit          uint64   `protobuf:"varint,3,opt,name=streamLimit,proto3" json:"streamLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poster) Reset()         { *m = Poster{} }
func (m *Poster) String() string { return proto.CompactTextString(m) }
func (*Poster) ProtoMessage()    {}
func (*Poster) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *Poster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poster.Unmarshal(m, b)
}
func (m *Poster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poster.Marshal(b, m, deterministic)
}
func (m *Poster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poster.Merge(m, src)
}
func (m *Poster) XXX_Size() int {
	return xxx_messageInfo_Poster.Size(m)
}
func (m *Poster) XXX_DiscardUnknown() {
	xxx_messageInfo_Poster.DiscardUnknown(m)
}

var xxx_messageInfo_Poster proto.InternalMessageInfo

func (m *Poster) GetBalance() *BigInt {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *Poster) GetOrderLimit() uint64 {
	if m != nil {
		return m.OrderLimit
	}
	return 0
}

func (m *Poster) GetStreamLimit() uint64 {
	if m != nil {
		return m.StreamLimit
	}
	return 0
}

type RateLimit struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Limit                uint64   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateLimit) Reset()         { *m = RateLimit{} }
func (m *RateLimit) String() string { return proto.CompactTextString(m) }
func (*RateLimit) ProtoMessage()    {}
func (*RateLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *RateLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateLimit.Unmarshal(m, b)
}
func (m *RateLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateLimit.Marshal(b, m, deterministic)
}
func (m *RateLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateLimit.Merge(m, src)
}
func (m *RateLimit) XXX_Size() int {
	return xxx_messageInfo_RateLimit.Size(m)
}
func (m *RateLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_RateLimit.DiscardUnknown(m)
}

var xxx_messageInfo_RateLimit proto.InternalMessageInfo

func (m *RateLimit) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RateLimit) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

//*
// SignedTransaction.
//
// This is the only Transaction accepted by the node. It's composed by a Transaction and it's Proof.
type SignedTransaction struct {
	Proof                *Proof       `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	Tx                   *Transaction `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SignedTransaction) Reset()         { *m = SignedTransaction{} }
func (m *SignedTransaction) String() string { return proto.CompactTextString(m) }
func (*SignedTransaction) ProtoMessage()    {}
func (*SignedTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *SignedTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedTransaction.Unmarshal(m, b)
}
func (m *SignedTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedTransaction.Marshal(b, m, deterministic)
}
func (m *SignedTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedTransaction.Merge(m, src)
}
func (m *SignedTransaction) XXX_Size() int {
	return xxx_messageInfo_SignedTransaction.Size(m)
}
func (m *SignedTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_SignedTransaction proto.InternalMessageInfo

func (m *SignedTransaction) GetProof() *Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *SignedTransaction) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

//*
// Proof is used to sign a Transaction and produce a SignedTransaction.
type Proof struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Proof) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

//*
// Transaction
type Transaction struct {
	// Types that are valid to be assigned to Data:
	//	*Transaction_Rebalance
	//	*Transaction_Witness
	Data                 isTransaction_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

type isTransaction_Data interface {
	isTransaction_Data()
}

type Transaction_Rebalance struct {
	Rebalance *TransactionRebalance `protobuf:"bytes,1,opt,name=rebalance,proto3,oneof"`
}

type Transaction_Witness struct {
	Witness *TransactionWitness `protobuf:"bytes,2,opt,name=witness,proto3,oneof"`
}

func (*Transaction_Rebalance) isTransaction_Data() {}

func (*Transaction_Witness) isTransaction_Data() {}

func (m *Transaction) GetData() isTransaction_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetRebalance() *TransactionRebalance {
	if x, ok := m.GetData().(*Transaction_Rebalance); ok {
		return x.Rebalance
	}
	return nil
}

func (m *Transaction) GetWitness() *TransactionWitness {
	if x, ok := m.GetData().(*Transaction_Witness); ok {
		return x.Witness
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Transaction) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Transaction_Rebalance)(nil),
		(*Transaction_Witness)(nil),
	}
}

//*
// TransactionRebalance
type TransactionRebalance struct {
	Limits               []*RateLimit `protobuf:"bytes,1,rep,name=limits,proto3" json:"limits,omitempty"`
	RoundInfo            *RoundInfo   `protobuf:"bytes,2,opt,name=round_info,json=roundInfo,proto3" json:"round_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TransactionRebalance) Reset()         { *m = TransactionRebalance{} }
func (m *TransactionRebalance) String() string { return proto.CompactTextString(m) }
func (*TransactionRebalance) ProtoMessage()    {}
func (*TransactionRebalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *TransactionRebalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRebalance.Unmarshal(m, b)
}
func (m *TransactionRebalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRebalance.Marshal(b, m, deterministic)
}
func (m *TransactionRebalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRebalance.Merge(m, src)
}
func (m *TransactionRebalance) XXX_Size() int {
	return xxx_messageInfo_TransactionRebalance.Size(m)
}
func (m *TransactionRebalance) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRebalance.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRebalance proto.InternalMessageInfo

func (m *TransactionRebalance) GetLimits() []*RateLimit {
	if m != nil {
		return m.Limits
	}
	return nil
}

func (m *TransactionRebalance) GetRoundInfo() *RoundInfo {
	if m != nil {
		return m.RoundInfo
	}
	return nil
}

//*
// TransactionWitness performs state modification of Stake Event transactions (modify staker's balance).
// This transaction should be originated from the validator nodes.
type TransactionWitness struct {
	Subject              TransactionWitness_Subject `protobuf:"varint,1,opt,name=subject,proto3,enum=types.TransactionWitness_Subject" json:"subject,omitempty"`
	Amount               *BigInt                    `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Block                uint64                     `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
	Address              string                     `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey            []byte                     `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Id                   []byte                     `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TransactionWitness) Reset()         { *m = TransactionWitness{} }
func (m *TransactionWitness) String() string { return proto.CompactTextString(m) }
func (*TransactionWitness) ProtoMessage()    {}
func (*TransactionWitness) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *TransactionWitness) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionWitness.Unmarshal(m, b)
}
func (m *TransactionWitness) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionWitness.Marshal(b, m, deterministic)
}
func (m *TransactionWitness) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionWitness.Merge(m, src)
}
func (m *TransactionWitness) XXX_Size() int {
	return xxx_messageInfo_TransactionWitness.Size(m)
}
func (m *TransactionWitness) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionWitness.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionWitness proto.InternalMessageInfo

func (m *TransactionWitness) GetSubject() TransactionWitness_Subject {
	if m != nil {
		return m.Subject
	}
	return TransactionWitness_POSTER
}

func (m *TransactionWitness) GetAmount() *BigInt {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TransactionWitness) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *TransactionWitness) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *TransactionWitness) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TransactionWitness) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterEnum("types.TransactionWitness_Subject", TransactionWitness_Subject_name, TransactionWitness_Subject_value)
	proto.RegisterType((*BigInt)(nil), "types.BigInt")
	proto.RegisterType((*RoundInfo)(nil), "types.RoundInfo")
	proto.RegisterType((*ConsensusParams)(nil), "types.ConsensusParams")
	proto.RegisterType((*Poster)(nil), "types.Poster")
	proto.RegisterType((*RateLimit)(nil), "types.RateLimit")
	proto.RegisterType((*SignedTransaction)(nil), "types.SignedTransaction")
	proto.RegisterType((*Proof)(nil), "types.Proof")
	proto.RegisterType((*Transaction)(nil), "types.Transaction")
	proto.RegisterType((*TransactionRebalance)(nil), "types.TransactionRebalance")
	proto.RegisterType((*TransactionWitness)(nil), "types.TransactionWitness")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x4f, 0x4f, 0x13, 0x41,
	0x14, 0xa7, 0x4b, 0xbb, 0x75, 0x5f, 0x5b, 0x84, 0x17, 0xd4, 0x1a, 0x94, 0xe0, 0x06, 0x23, 0x07,
	0x83, 0x49, 0xd5, 0x13, 0xa7, 0x02, 0x1a, 0x88, 0x18, 0x9a, 0xa1, 0xd1, 0x83, 0x07, 0x32, 0xed,
	0x4e, 0xcb, 0xc8, 0x76, 0xa6, 0xce, 0xcc, 0x2a, 0xfd, 0x08, 0x7e, 0x4c, 0x3f, 0x88, 0x89, 0xd9,
	0x99, 0x59, 0xba, 0x85, 0x7a, 0xeb, 0xef, 0xcf, 0xbc, 0xf9, 0xcd, 0x7b, 0x6f, 0x0b, 0x0d, 0x33,
	0x9b, 0x32, 0xbd, 0x3f, 0x55, 0xd2, 0x48, 0xac, 0x59, 0x10, 0x6f, 0x43, 0x78, 0xc8, 0xc7, 0xa7,
	0xc2, 0xe0, 0x26, 0xd4, 0x7e, 0xd2, 0x34, 0x63, 0xed, 0xca, 0x4e, 0x65, 0xaf, 0x49, 0x1c, 0x88,
	0x25, 0x44, 0x44, 0x66, 0x22, 0x39, 0x15, 0x23, 0x89, 0x8f, 0x21, 0x14, 0xd9, 0x64, 0xc0, 0x94,
	0xf5, 0x54, 0x89, 0x47, 0xb8, 0x05, 0x91, 0x36, 0x54, 0x19, 0x7d, 0x49, 0x4d, 0x3b, 0xb0, 0xd2,
	0x03, 0x47, 0x74, 0x0d, 0x3e, 0x81, 0x3a, 0x13, 0x89, 0x95, 0x56, 0xdd, 0xa9, 0x1c, 0x76, 0xed,
	0x85, 0x29, 0x9f, 0x70, 0xd3, 0xae, 0x5a, 0xda, 0x81, 0xf8, 0x4f, 0x05, 0x1e, 0x1e, 0x49, 0xa1,
	0x99, 0xd0, 0x99, 0xee, 0x51, 0x45, 0x27, 0x1a, 0x5f, 0xc3, 0xc6, 0x47, 0x2e, 0x68, 0xca, 0xcd,
	0xac, 0x7f, 0xa5, 0x98, 0xbe, 0x92, 0x69, 0x62, 0x23, 0xb4, 0xc8, 0x7d, 0x01, 0x77, 0xa0, 0xd1,
	0x63, 0x8a, 0xcb, 0xe4, 0xcc, 0x56, 0x0f, 0xac, 0xaf, 0x4c, 0x61, 0x0c, 0x4d, 0x0f, 0x99, 0x18,
	0x9b, 0x2b, 0x9b, 0xab, 0x45, 0x16, 0x38, 0xdc, 0x85, 0xd6, 0x67, 0x7a, 0x73, 0xae, 0x12, 0xa6,
	0x0e, 0x67, 0x86, 0x69, 0x9b, 0xb2, 0x45, 0x16, 0x49, 0x7c, 0x07, 0x8f, 0x8e, 0xa4, 0x18, 0x71,
	0x35, 0xa1, 0x86, 0x4b, 0x31, 0x4f, 0x57, 0xb3, 0xee, 0xe5, 0x62, 0xac, 0x21, 0xec, 0x49, 0x6d,
	0x98, 0xc2, 0x57, 0x50, 0x1f, 0xd0, 0x94, 0x8a, 0xa1, 0x6b, 0x7b, 0xa3, 0xd3, 0xda, 0x77, 0x43,
	0x72, 0x43, 0x21, 0x85, 0x8a, 0xdb, 0x00, 0x32, 0xbf, 0x76, 0xfe, 0xa6, 0x2a, 0x29, 0x31, 0xf9,
	0xa3, 0xb5, 0x51, 0x8c, 0x4e, 0x9c, 0xc1, 0x75, 0xba, 0x4c, 0xc5, 0x07, 0x10, 0x11, 0x6a, 0x98,
	0xb3, 0xb7, 0xa1, 0x4e, 0x93, 0x44, 0x31, 0xad, 0xed, 0xbd, 0x11, 0x29, 0xe0, 0x7c, 0x2a, 0x41,
	0x79, 0x2a, 0xdf, 0x60, 0xe3, 0x82, 0x8f, 0x05, 0x4b, 0xfa, 0x8a, 0x0a, 0x4d, 0x87, 0xf9, 0x7b,
	0x30, 0x86, 0xda, 0x54, 0x49, 0x39, 0xf2, 0xd1, 0x9b, 0x3e, 0x7a, 0x2f, 0xe7, 0x88, 0x93, 0x30,
	0x86, 0xc0, 0xdc, 0xd8, 0x5a, 0x8d, 0x0e, 0x7a, 0x43, 0xa9, 0x06, 0x09, 0xcc, 0x4d, 0x7c, 0x0c,
	0x35, 0x7b, 0x06, 0x9f, 0x03, 0x4c, 0xb3, 0x41, 0xca, 0x87, 0x97, 0xd7, 0x6c, 0xe6, 0xf7, 0x30,
	0x72, 0xcc, 0x27, 0x36, 0xc3, 0x67, 0x10, 0x69, 0x3e, 0x16, 0xd4, 0x64, 0x8a, 0xd9, 0x92, 0x4d,
	0x32, 0x27, 0xe2, 0xdf, 0x15, 0x68, 0x94, 0xd3, 0x1d, 0x40, 0xa4, 0xd8, 0x62, 0x73, 0xb7, 0x96,
	0x04, 0x28, 0x2c, 0x27, 0x2b, 0x64, 0xee, 0xc7, 0xf7, 0x50, 0xff, 0xc5, 0x8d, 0xc8, 0xfb, 0xe3,
	0xb2, 0x3f, 0xbd, 0x7f, 0xf4, 0xab, 0x33, 0x9c, 0xac, 0x90, 0xc2, 0x7b, 0x18, 0x42, 0x35, 0xa1,
	0x86, 0xc6, 0x3f, 0x60, 0x73, 0xd9, 0x1d, 0xb8, 0x07, 0xa1, 0xed, 0x67, 0xde, 0xf5, 0xd5, 0xbd,
	0x46, 0x67, 0xdd, 0x57, 0xbd, 0x1d, 0x0c, 0xf1, 0x3a, 0xbe, 0x01, 0x50, 0xf9, 0x77, 0x77, 0xc9,
	0xc5, 0x48, 0xfa, 0x0c, 0xb7, 0xee, 0xe2, 0x83, 0x24, 0x91, 0x2a, 0x7e, 0xc6, 0x7f, 0x2b, 0x80,
	0xf7, 0xc3, 0xe1, 0x01, 0xd4, 0x75, 0x36, 0xf8, 0xce, 0x86, 0xc6, 0xf6, 0x60, 0xad, 0xf3, 0xe2,
	0xbf, 0x0f, 0xd9, 0xbf, 0x70, 0x46, 0x52, 0x9c, 0xc0, 0x97, 0x10, 0xd2, 0x89, 0xcc, 0x84, 0xf1,
	0x01, 0xee, 0x2c, 0xa7, 0x17, 0xf3, 0x95, 0x19, 0xa4, 0x72, 0x78, 0xed, 0xb7, 0xce, 0x81, 0xf2,
	0x8a, 0x55, 0x17, 0x57, 0x6c, 0x71, 0xcc, 0xb5, 0xbb, 0x63, 0x5e, 0x83, 0x80, 0x27, 0xed, 0xd0,
	0xd2, 0x01, 0x4f, 0xe2, 0x5d, 0xa8, 0xfb, 0x64, 0x08, 0x10, 0xf6, 0xce, 0x2f, 0xfa, 0x1f, 0xc8,
	0xfa, 0x0a, 0xb6, 0x20, 0xfa, 0xd2, 0x3d, 0x3b, 0x3d, 0xee, 0xf6, 0xcf, 0xc9, 0x7a, 0x65, 0x10,
	0xda, 0xbf, 0xb5, 0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xef, 0x24, 0x26, 0xe5, 0x04,
	0x00, 0x00,
}
