project_name: kosu

builds:
  - id: kosud
    binary: kosud
    main: ./cmd/kosud/main.go
    ldflags: &ldflags
      - -s -w -X github.com/ParadigmFoundation/kosu-monorepo/packages/go-kosu/version.Version={{.Version}}
      - -X github.com/ParadigmFoundation/kosu-monorepo/packages/go-kosu/version.GitCommit={{.ShortCommit}}

    goos:
      - linux
    goarch:
      - amd64

  - id: kosu-cli
    binary: kosu-cli
    main: ./cmd/kosu-cli/main.go
    ldflags: *ldflags
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: kosu
    name_template: "{{ .ProjectName }}-{{ .Os }}"

dockers:
  - dockerfile: Dockerfile.binaries
    goos: linux
    goarch: amd64
    binaries:
      - kosud
      - kosu-cli
    image_templates:
      - gcr.io/kosu-test-network/go-kosu:latest

checksum:
  name_template: 'checksums.txt'
