version: '3'

services:
  node0:
    container_name: node0
    build: .
    command: ["/go-kosu/kosud", "--home", "/go-kosu/testnet/node0"]
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    build: .
    command: ["/go-kosu/kosud", "--home", "/go-kosu/testnet/node1"]
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node2:
    container_name: node2
    build: .
    command: ["/go-kosu/kosud", "--home", "/go-kosu/testnet/node2"]
    networks:
      localnet:
        ipv4_address: 192.167.10.4

  node3:
    container_name: node3
    build: .
    command: ["/go-kosu/kosud", "--home", "/go-kosu/testnet/node3"]
    networks:
      localnet:
        ipv4_address: 192.167.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
